### ISSUE TITLE
Add note about original author of node-text

### ISSUE THREAD

**Issue by MatthewRock** [TeMPOraL/scrap-gumtree#1]
It would be nice if the original author of `node-text` function was mentioned. It looks like the code is exactly the same as [here](http://readevalprint.tumblr.com/post/80764585017/web-scraping-with-common-lisp-introduction), and author mentions [webgunk](https://github.com/tshatrov/webgunk) (which he wrote himself). Attribution is always nice.

**Comment by TeMPOraL** [comment]
You're right, of course. A mistake of omission on my part.

I was using his code for the node-text and strip-whitespace functions in the scrapper, which was written during KrakLisp meetup, and quickly dumped the code to GitHub for participants to review.
